import type { StoreProduct } from "./types";

export const storeProducts: StoreProduct[] = [
  { id: 1, category: "Jeans", subtype: "Slim", name: "Raw Indigo Slim", fit: "Slim", price: 1299, color: "#274c77", image: "/assets/jean-raw-indigo.jpg", gallery: ["/assets/jean-raw-indigo.jpg", "/assets/jean-washed-black.jpg", "/assets/denim-construction-macros.jpg"], sizes: ["30", "32", "34", "36"] },
  { id: 2, category: "Jeans", subtype: "Regular", name: "Stone Blue Regular", fit: "Regular", price: 1199, color: "#426a8c", image: "/assets/jean-stone-blue.jpg", gallery: ["/assets/jean-stone-blue.jpg", "/assets/jean-cloud-blue.jpg", "/assets/denim-anatomy.jpg"], sizes: ["30", "32", "34", "36"] },
  { id: 3, category: "Jeans", subtype: "Skinny", name: "Washed Black Taper", fit: "Skinny", price: 1399, color: "#172f4d", image: "/assets/jean-washed-black.jpg", gallery: ["/assets/jean-washed-black.jpg", "/assets/jean-raw-indigo.jpg", "/assets/denim-construction-macros.jpg"], sizes: ["28", "30", "32", "34"] },
  { id: 4, category: "Jeans", subtype: "Relaxed", name: "Cloud Wash Loose", fit: "Relaxed", price: 1099, color: "#5b7183", image: "/assets/jean-cloud-blue.jpg", gallery: ["/assets/jean-cloud-blue.jpg", "/assets/jean-stone-blue.jpg", "/assets/denim-anatomy.jpg"], sizes: ["30", "32", "34", "36"] },
  { id: 5, category: "Jeans", subtype: "Relaxed", name: "Raw Indigo Wide", fit: "Relaxed", price: 1599, color: "#142a43", image: "/assets/jean-raw-indigo.jpg", gallery: ["/assets/jean-raw-indigo.jpg", "/assets/jean-washed-black.jpg", "/assets/denim-anatomy.jpg"], sizes: ["28", "30", "32", "34", "36"] },
  { id: 6, category: "Jeans", subtype: "Regular", name: "Stone Blue Straight", fit: "Regular", price: 1499, color: "#70879b", image: "/assets/jean-stone-blue.jpg", gallery: ["/assets/jean-stone-blue.jpg", "/assets/jean-cloud-blue.jpg", "/assets/denim-construction-macros.jpg"], sizes: ["30", "32", "34", "36", "38"] },
  { id: 7, category: "Jeans", subtype: "Slim", name: "Midnight Taper", fit: "Slim", price: 1699, color: "#111c2c", image: "/assets/jean-washed-black.jpg", gallery: ["/assets/jean-washed-black.jpg", "/assets/jean-raw-indigo.jpg", "/assets/denim-construction-macros.jpg"], sizes: ["28", "30", "32", "34"] },
  { id: 8, category: "Jeans", subtype: "Relaxed", name: "Cloud Blue Volume", fit: "Relaxed", price: 1399, color: "#91a5b3", image: "/assets/jean-cloud-blue.jpg", gallery: ["/assets/jean-cloud-blue.jpg", "/assets/jean-stone-blue.jpg", "/assets/denim-anatomy.jpg"], sizes: ["30", "32", "34", "36", "38"] },
  { id: 9, category: "Henley", subtype: "Classic Slub", name: "Ecru Slub Henley", fit: "Regular", price: 1499, color: "#e8dfcf", image: "/assets/henley-ecru.webp", gallery: ["/assets/henley-ecru.webp", "/assets/henley-craft-macro.webp", "/assets/henley-editorial.webp"], sizes: ["S", "M", "L", "XL", "XXL"], sku: "DK-H-0009", stock: 32, description: "A breathable cotton-slub Henley with a reinforced three-button placket and an easy everyday drape.", active: true },
  { id: 10, category: "Henley", subtype: "Heavyweight Rib", name: "Oxblood Rib Henley", fit: "Regular", price: 1699, color: "#6e302f", image: "/assets/henley-oxblood.webp", gallery: ["/assets/henley-oxblood.webp", "/assets/henley-craft-macro.webp", "/assets/henley-editorial.webp"], sizes: ["S", "M", "L", "XL", "XXL"], sku: "DK-H-0010", stock: 28, description: "A substantial rib-cuff Henley with clean structure, tonal reinforcement and a softened oxblood finish.", active: true },
  { id: 11, category: "Henley", subtype: "Waffle Knit", name: "Indigo Waffle Henley", fit: "Regular", price: 1799, color: "#172744", image: "/assets/henley-indigo-waffle.webp", gallery: ["/assets/henley-indigo-waffle.webp", "/assets/henley-craft-macro.webp", "/assets/landing-uniform-henley-denim.webp"], sizes: ["S", "M", "L", "XL", "XXL"], sku: "DK-H-0011", stock: 26, description: "A deep-indigo waffle Henley with dimensional texture, a stable three-button placket and an easy structured drape.", active: true },
  { id: 12, category: "Henley", subtype: "Classic Slub", name: "Moss Slub Henley", fit: "Relaxed", price: 1599, color: "#66664a", image: "/assets/henley-olive-slub.webp", gallery: ["/assets/henley-olive-slub.webp", "/assets/henley-craft-macro.webp", "/assets/henley-editorial.webp"], sizes: ["S", "M", "L", "XL", "XXL"], sku: "DK-H-0012", stock: 34, description: "Breathable moss cotton slub, softened at the surface and cut with relaxed room for everyday layering.", active: true },
  { id: 13, category: "Henley", subtype: "Short Sleeve", name: "Charcoal Short Henley", fit: "Regular", price: 1399, color: "#333536", image: "/assets/henley-charcoal-short.webp", gallery: ["/assets/henley-charcoal-short.webp", "/assets/henley-craft-macro.webp", "/assets/landing-uniform-henley-denim.webp"], sizes: ["S", "M", "L", "XL", "XXL"], sku: "DK-H-0013", stock: 38, description: "A clean charcoal short-sleeve Henley with a close neckline and breathable weight for warmer days.", active: true },
  { id: 14, category: "Henley", subtype: "Heavyweight Rib", name: "Rust Rib Henley", fit: "Regular", price: 1899, color: "#a64f32", image: "/assets/henley-rust-rib.webp", gallery: ["/assets/henley-rust-rib.webp", "/assets/henley-craft-macro.webp", "/assets/henley-editorial.webp"], sizes: ["S", "M", "L", "XL", "XXL"], sku: "DK-H-0014", stock: 24, description: "A substantial rust rib Henley with anchored cuffs, warm depth and a structure that settles with wear.", active: true },
];

export const reviews = [
  ["Aarav S.", "The fit is unreal. It feels broken-in from day one.", "5.0"],
  ["Maya R.", "Finally, pieces that work through a full day and still look sharp.", "4.9"],
  ["Kabir P.", "Great color, clean finish, and a silhouette that holds.", "5.0"],
  ["Nia K.", "I came back for a second pair within a week.", "4.8"],
];

export const money = (value: number) => `Rs. ${value.toLocaleString("en-IN")}`;
