import { ArrowLeft, Check, ChevronRight, Mail, MapPin, PackageCheck, Phone, Truck } from "lucide-react";
import { money } from "../../storefront/data";
import { AdminHeader } from "../components/AdminHeader";
import { orderStatuses, orderTotal } from "../data";
import type { AdminOrder, AdminRoute, OrderStatus } from "../types";

export function OrderDetailPage({ order, go, updateStatus }: { order: AdminOrder; go: AdminRoute; updateStatus: (status: OrderStatus) => void }) {
  const statusIndex = orderStatuses.indexOf(order.status);
  const nextStatus = orderStatuses[Math.min(statusIndex + 1, orderStatuses.length - 1)];
  const subtotal = order.items.reduce((total, item) => total + item.price * item.quantity, 0);
  return <><AdminHeader eyebrow={`Order #${order.id}`} title="Order details"><button className="admin-secondary" onClick={() => go("orders")}><ArrowLeft /> All orders</button></AdminHeader><div className="admin-detail-layout"><div className="admin-detail-main"><section className="order-status-panel"><div className="admin-panel-title"><div><p className="eyebrow">Delivery progress</p><h2>{order.status}</h2></div><Truck /></div><div className="admin-status-track">{orderStatuses.map((status, index) => <div className={index <= statusIndex ? "done" : ""} key={status}><i>{index <= statusIndex ? <Check /> : index + 1}</i><span>{status}</span></div>)}</div>{order.status !== "Delivered" && <button className="admin-primary full" onClick={() => updateStatus(nextStatus)}>Move to {nextStatus} <ChevronRight /></button>}</section><section className="admin-order-items"><div className="admin-panel-title"><div><p className="eyebrow">Purchase</p><h2>Order items</h2></div><span>{order.items.length} pieces</span></div>{order.items.map((item) => <article key={`${item.productId}-${item.size}`}><img src={item.image} alt={item.name} /><div><b>{item.name}</b><span>Waist {item.size} / Quantity {item.quantity}</span></div><strong>{money(item.price * item.quantity)}</strong></article>)}</section></div><aside className="admin-order-aside"><section><p className="eyebrow">Customer</p><h3>{order.customer.name}</h3><p><Phone /> {order.customer.phone}</p><p><Mail /> {order.customer.email}</p></section><section><p className="eyebrow">Delivery address</p><p><MapPin /> <span>{order.address}<br />{order.city} - {order.pin}</span></p></section><section><p className="eyebrow">Payment summary</p><p><span>Subtotal</span><b>{money(subtotal)}</b></p>{Boolean(order.discount) && <p><span>Discount</span><b>-{money(order.discount || 0)}</b></p>}<p><span>Delivery</span><b>Free</b></p><p className="admin-total"><span>Total</span><b>{money(orderTotal(order))}</b></p><small><PackageCheck /> {order.payment} payment</small></section></aside></div></>;
}
